name: Build
on: [push]

jobs:
  build_deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build
        run: npm install && npm run-script build

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: |
            ./_site
          retention-days: 2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: charlesfahselt.com
